# Generated by Django 6.0.4 on 2026-04-17 16:52

import django.db.models.deletion
import model_index.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source', models.TextField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Benchmark',
                'verbose_name_plural': 'Benchmarks',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_template', models.TextField()),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
            },
        ),
        migrations.CreateModel(
            name='BenchmarkSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_sets', to='model_index.benchmark')),
            ],
            options={
                'verbose_name': 'Benchmark Set',
                'verbose_name_plural': 'Benchmark Sets',
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
                'constraints': [models.UniqueConstraint(fields=('author', 'model_name', 'version'), name='model_fullref')],
            },
        ),
        migrations.CreateModel(
            name='MLModelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_note', models.TextField(blank=True, null=True)),
                ('description', models.TextField(default='')),
                ('dependencies', models.JSONField(blank=True, default=dict)),
                ('profiling', models.JSONField(blank=True, default=dict)),
                ('benchmarks', models.ManyToManyField(related_name='model_records', through='model_index.BenchmarkSet', to='model_index.benchmark')),
                ('model_fullref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='model_index.mlmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_records', to=settings.AUTH_USER_MODEL)),
                ('prompts', models.ManyToManyField(related_name='model_records', to='model_index.prompt')),
            ],
            options={
                'verbose_name': 'MLModel Record',
                'verbose_name_plural': 'MLModel Records',
            },
        ),
        migrations.CreateModel(
            name='MLArchitectureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=model_index.models.architecture_file_upload_path)),
                ('description', models.TextField(blank=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architecture', to='model_index.mlmodelrecord')),
            ],
            options={
                'verbose_name': 'Architecture File',
                'verbose_name_plural': 'Architecture Files',
            },
        ),
        migrations.AddField(
            model_name='benchmarkset',
            name='model_fullref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_sets', to='model_index.mlmodelrecord'),
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sphere', models.CharField(max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_raw', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('datasets', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_fullref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to='model_index.mlmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Use Case',
                'verbose_name_plural': 'Use Cases',
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_fullref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='model_index.mlmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Review',
                'verbose_name_plural': 'User Reviews',
                'unique_together': {('user_id', 'model_fullref')},
            },
        ),
    ]
