# Generated by Django 4.2.30 on 2026-04-17 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source', models.TextField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Benchmark',
                'verbose_name_plural': 'Benchmarks',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='ProfilingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('json', 'JSON')], default='string', max_length=50)),
            ],
            options={
                'verbose_name': 'Profiling Type',
                'verbose_name_plural': 'Profiling Types',
            },
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sphere', models.CharField(max_length=255)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('is_raw', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('datasets', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to='model_index.model')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Use Case',
                'verbose_name_plural': 'Use Cases',
            },
        ),
        migrations.CreateModel(
            name='Profiling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiling_data', to='model_index.model')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiling_records', to='model_index.profilingtype')),
            ],
            options={
                'verbose_name': 'Profiling',
                'verbose_name_plural': 'Profiling',
            },
        ),
        migrations.CreateModel(
            name='ModelRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.JSONField(blank=True, default=list, help_text='List of file paths/media for model architecture')),
                ('custom_note', models.TextField(blank=True, null=True)),
                ('description', models.TextField(default='')),
                ('dependencies', models.TextField(blank=True, help_text='Path to markdown file or simple text')),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='model_index.model')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Record',
                'verbose_name_plural': 'Model Records',
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='model_index.model')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Review',
                'verbose_name_plural': 'User Reviews',
                'unique_together': {('user_id', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='BenchmarkSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_sets', to='model_index.benchmark')),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_sets', to='model_index.model')),
            ],
            options={
                'verbose_name': 'Benchmark Set',
                'verbose_name_plural': 'Benchmark Sets',
                'unique_together': {('model_name', 'benchmark')},
            },
        ),
    ]
