# Generated by Django 6.0.4 on 2026-04-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='is_quantized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mlmodelrecord',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mlmodelrecord',
            name='custom_name',
            field=models.CharField(default='custom_Name1', max_length=100),
            preserve_default=False,
        ),
    ]
