# Generated by Django 6.0.4 on 2026-04-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_index', '0002_mlmodel_is_quantized_mlmodelrecord_badges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
    ]
