# Generated by Django 6.0.4 on 2026-04-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_index', '0004_prompt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
