# Generated by Django 6.0.4 on 2026-04-24 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_index', '0005_alter_prompt_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='usecase',
            old_name='is_raw',
            new_name='is_model_modified',
        ),
        migrations.AddConstraint(
            model_name='mlmodelrecord',
            constraint=models.UniqueConstraint(fields=('user_id', 'model_fullref'), name='unique_user_model_record'),
        ),
    ]
