# Generated by Django 6.0.4 on 2026-04-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_index', '0006_rename_is_raw_usecase_is_model_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='param_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
