# Generated by Django 6.0.4 on 2026-04-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_index', '0007_mlmodel_param_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodelrecord',
            name='badges',
        ),
        migrations.AddField(
            model_name='mlmodelrecord',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='model_records', to='model_index.badge'),
        ),
    ]
