# Generated by Django 6.0.4 on 2026-04-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_index', '0008_remove_mlmodelrecord_badges_mlmodelrecord_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodelrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
