# Generated by Django 6.0.4 on 2026-04-27 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_index', '0009_mlmodelrecord_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='rank',
            field=models.SmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
